-- Super+Shift+L: hide the currently active special workspace (no-op if none open)
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("bash -c 'ws=$(hyprctl monitors -j | jq -r \".[].specialWorkspace.name | select(length > 0)\" | head -1); [ -n \"$ws\" ] && hyprctl eval \"hl.dispatch(hl.dsp.workspace.toggle_special(\\\"${ws#special:}\\\"))\"'"))

-- Super+S: show QuickShell scratchpad picker + enter submap for number keys
hl.bind(mainMod .. " + S", function()
	hl.dispatch(hl.dsp.global("quickshell:scratchpadPicker"))
	hl.dispatch(hl.dsp.submap("scratchpad_pick"))
end)

hl.define_submap("scratchpad_pick", "reset", function()
	hl.bind("1", function()
		hl.dispatch(hl.dsp.workspace.toggle_special("term"))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadPicker"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("2", function()
		hl.dispatch(hl.dsp.workspace.toggle_special("zen"))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadPicker"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("3", function()
		hl.dispatch(hl.dsp.workspace.toggle_special("spotify"))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadPicker"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("escape", function()
		hl.dispatch(hl.dsp.global("quickshell:scratchpadPicker"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
end)

-- Super+L: show QuickShell move-to-scratchpad picker + enter submap
hl.bind(mainMod .. " + L", function()
	hl.dispatch(hl.dsp.global("quickshell:scratchpadMover"))
	hl.dispatch(hl.dsp.submap("scratchpad_move"))
end)

hl.define_submap("scratchpad_move", "reset", function()
	hl.bind("1", function()
		hl.dispatch(hl.dsp.window.move({ workspace = "special:term" }))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadMover"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("2", function()
		hl.dispatch(hl.dsp.window.move({ workspace = "special:zen" }))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadMover"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("3", function()
		hl.dispatch(hl.dsp.window.move({ workspace = "special:spotify" }))
		hl.dispatch(hl.dsp.global("quickshell:scratchpadMover"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
	hl.bind("escape", function()
		hl.dispatch(hl.dsp.global("quickshell:scratchpadMover"))
		hl.dispatch(hl.dsp.submap("reset"))
	end)
end)
