[pyprland]
plugins = [
    "scratchpads",
    "gamemode",
    "magnify",
    "expose",
    "fetch_client_menu",
    "menu",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty  --app-id kitty-dropterm"
class = "kitty-dropterm"
size = "85% 70%"
max_size = "1920px 100%"
margin = 50


[scratchpads.spotify]
command = "spotify --disable-gpu"
class = "Spotify"
animation = "fromRight"
size = "75% 70%"
lazy = true
unfocus = "hide"

[scratchpads.discord]
command = "discord"
class = "discord"
animation = "fromLeft"
size = "75% 70%"
lazy = true
unfocus = "hide"

[scratchpads.obs]
command = "obs"
class = "com.obsproject.Studio"
animation = "fromLeft"
size = "75% 70%"
lazy = true
unfocus = "hide"

