[pyprland]
plugins = [
    "scratchpads",
    "gamemode",
    "magnify",
    "expose",
    "fetch_client_menu",
    "menu",
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "85% 70%"
max_size = "1920px 100%"
margin = 50


[scratchpads.zen]
command = "zen-browser"
class = "zen"
animation = "fromBottom"
size = "75% 70%"
lazy = true

[scratchpads.spotify]
command = "spotify"
class = "Spotify"
animation = "fromRight"
size = "75% 70%"
lazy = true
unfocus = "hide"


[menu]
