[pyprland]
plugins = [
    "scratchpads",
    "gamemode",
    "magnify",
    "expose",
    "fetch_client_menu",
]

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
animation = "fromTop"
size = "70% 60%"
max_size = "1920px 100%"
margin = 40
hide_delay = 0
lazy = true

[scratchpads.mongodb-compass]
command = "mongodb-compass --ignore-additional-command-line-flags --password-store='gnome-libsecret'"
class = "MongoDB Compass"
animation = "fromTop"
size = "95% 90%"
lazy = true

