source = ~/.config/hypr/config/ui/myColors.conf
source = ~/.config/hypr/config/keybinds/keybind.conf
source = ~/.config/hypr/config/ui/animations/animation.conf
source = ~/.config/hypr/config/autostarts/execOnce.conf
source = ~/.config/hypr/config/variables/env(s).conf
source = ./hyprviz.conf
source = ~/.config/hypr/config/ui/decor.conf


monitor = eDP-1, 1920x1080@144, 0x0, 1.0 

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = false 
    # vrr = 1

}
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    repeat_rate=80
    repeat_delay=190
    follow_mouse = 1

    sensitivity = 1 

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = 0
}

windowrule = match:initial_class org.gnome.eog, float 1, size 1200 700

